/usr/lib/*/libpt*.a
/usr/lib/*/libopal*.a


/usr/include/ptlib*.h

/usr/include/ptlib
/usr/include/ptlib/*

/usr/include/ptclib
/usr/include/ptclib/*

/usr/include/opal
/usr/include/opal/*

/usr/share/ptlib
/usr/share/ptlib/*

/usr/share/opal
/usr/share/opal/*

#
# Resiprocate files
#
/usr/lib/*/libdum.a
/usr/lib/*/libresip.a
/usr/lib/*/libresipares.a
/usr/lib/*/librutil.a
/usr/share/man/man3/ares_*
/usr/include/resip
/usr/include/resip/*
/usr/include/rutil
/usr/include/rutil/*

#
# NodeJS files
#
/usr/include/node
/usr/include/node/*
